apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: nginx-application
        paths:
          - /var/log/containers/nginx-deployment-*_nginx_nginx-*.log
        prospector.scanner.symlinks: true
        prospector.scanner.fingerprint.length: 64
        parsers:
          - container:
              stream: all
              format: cri
    output.file:
      path: /collected-logs
      filename: nginx
      rotate_every_kb: 10240
      number_of_files: 7
      rotate_on_startup: false
