apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: nginx-gateway
        metrics_path: /metrics
        static_configs:
          - targets:
              - nginx-gateway.nginx-gateway.svc.cluster.local:9113
