apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-files
  namespace: nginx
data:
  index.html: |
    Hello world!
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      access_log /dev/stdout combined;
      error_log /dev/stderr warn;
      location / {
      }
    }
